### ISSUE TITLE
Error: 'join' can have side effects (nim 2.0)

### ISSUE THREAD

**Issue by ITwrx** [guzba/ready#2]
I get the following compile error when trying to compile with nim 2.0

```
/home/itwrx/.nimble/pkgs/ready-0.1.2/ready/connections.nim(55, 15) template/generic instantiation of `join` from here
/home/itwrx/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1855, 6) Error: 'join' can have side effects
> /home/itwrx/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1865, 17) Hint: 'join' calls `.sideEffect` '$'
>> /home/itwrx/.nimble/pkgs/ready-0.1.2/ready/connections.nim(46, 6) Hint: '$' called by 'join'
```
thanks

**Comment by guzba** [comment]
This has been fixed in release 0.1.4.

**Comment by ITwrx** [comment]
i uninstalled and reinstalled ready and i still get the following.

```
/home/itwrx/.nimble/pkgs2/ready-0.1.4-876e2ab213a5ef4a48f054a37cd420d1a1d2fa6c/ready/connections.nim(55, 15) template/generic instantiation of `join` from here
/home/itwrx/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1855, 6) Error: 'join' can have side effects
> /home/itwrx/.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim(1865, 17) Hint: 'join' calls `.sideEffect` '$'
>> /home/itwrx/.nimble/pkgs2/ready-0.1.4-876e2ab213a5ef4a48f054a37cd420d1a1d2fa6c/ready/connections.nim(46, 6) Hint: '$' called by 'join'
```

**Comment by ITwrx** [comment]
and now, after removing and reinstalling ready with 1.6.14 i get:

```
[my_app_dir]/models/user_model.nim(8, 15) Error: undeclared identifier: 'redis'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 2): 'ready' [module declared in [my_app_dir]/models/user_model.nim(1, 37)]
```
even though ready is installed in .nimble/pkgs, and imported in the same file as called in. Though, i'm guessing this is nimble/nim issue and not ready's fault...

**Comment by guzba** [comment]
Ah my mistake, it is fixed in 0.1.5 which I had not tagged yet. Just tagged now.

**Comment by ITwrx** [comment]
great! thanks
